### ISSUE TITLE
Uncaught Error: ENOENT: no such file or directory, open 'C:\tmp\atom.apib'

### ISSUE THREAD

**Issue by ajackson-sonardesign** [danielgtaylor/atom-api-blueprint-preview#24] opened 2015-04-02 14:16 UTC
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 0.189.0
**System**: Microsoft Windows 7 Professional 
**Thrown From**: [api-blueprint-preview](https://github.com/danielgtaylor/atom-api-blueprint-preview) package, v0.3.0

### Stack Trace

Uncaught Error: ENOENT: no such file or directory, open 'C:\tmp\atom.apib'

```
At C:\Users\Allen\AppData\Local\atom\app-0.189.0\resources\app\node_modules\q\q.js:128

Error: ENOENT: no such file or directory, open 'C:\tmp\atom.apib'
  at Error (native)
  at Object.fs.openSync (fs.js:544:18)
  at Object.module.(anonymous function) [as openSync] (ATOM_SHELL_ASAR.js:118:20)
  at Object.fs.writeFileSync (fs.js:1155:15)
  at ApiBlueprintPreviewView.module.exports.ApiBlueprintPreviewView.renderApiBlueprintText (C:\Users\Allen\.atom\packages\api-blueprint-preview\lib\api-blueprint-preview-view.coffee:83:8)
  at ApiBlueprintPreviewView.module.exports.ApiBlueprintPreviewView.renderApiBlueprint (C:\Users\Allen\.atom\packages\api-blueprint-preview\lib\api-blueprint-preview-view.coffee:80:8)
  at C:\Users\Allen\.atom\packages\api-blueprint-preview\lib\api-blueprint-preview.coffee:48:33
  at _fulfilled (C:\Users\Allen\AppData\Local\atom\app-0.189.0\resources\app\node_modules\q\q.js:794:54)
  at self.promiseDispatch.done (C:\Users\Allen\AppData\Local\atom\app-0.189.0\resources\app\node_modules\q\q.js:823:30)
  at Promise.promise.promiseDispatch (C:\Users\Allen\AppData\Local\atom\app-0.189.0\resources\app\node_modules\q\q.js:756:13)
  at C:\Users\Allen\AppData\Local\atom\app-0.189.0\resources\app\node_modules\q\q.js:516:49
  at flush (C:\Users\Allen\AppData\Local\atom\app-0.189.0\resources\app\node_modules\q\q.js:110:17)
  at process._tickCallback (node.js:357:13)

```

### Commands

```
     -1:46.6 core:page-down (atom-text-editor.editor)
 27x -1:45.8 core:page-up (atom-text-editor.editor)
  2x -1:12.0 core:page-down (atom-text-editor.editor)
 10x -1:05.8 core:move-up (atom-text-editor.editor)
  3x -1:04.5 core:delete (atom-text-editor.editor)
  2x -1:02.0 core:move-right (atom-text-editor.editor)
     -1:01.5 editor:move-to-end-of-word (atom-text-editor.editor)
     -1:01.0 core:move-left (atom-text-editor.editor)
     -0:59.6 core:move-down (atom-text-editor.editor)
  2x -0:59.6 core:delete (atom-text-editor.editor)
     -0:57.5 core:move-down (atom-text-editor.editor)
  5x -0:54.1 core:move-up (atom-text-editor.editor)
     -0:52.6 core:save (atom-text-editor.editor)
  2x -0:49.9 editor:move-to-first-character-of-line (atom-text-editor.editor)
  7x -0:49.3 core:select-down (atom-text-editor.editor)
  2x -0:28.7 api-blueprint-preview:toggle (atom-text-editor.editor)
```

### Config

```json
{}
```

### Installed Packages

```coffee
# User
api-blueprint-preview, v0.3.0

# Dev
No dev packages
```

**Comment by danielgtaylor** [comment] 2015-05-22 04:05
Are you still getting this error? As a workaround, what happens if you make a directory called `C:\tmp`?

**Comment by danielgtaylor** [comment] 2015-05-22 04:07
Actually, this is a duplicate of #17. We need to check if the directory exists first, and if not then either create it or use C:\temp or something.

**Closed by danielgtaylor** 2015-05-22 04:07 UTC
