### ISSUE TITLE
Compatibility with atom 0.189.0

### ISSUE THREAD

**Issue by neofreko** [danielgtaylor/atom-api-blueprint-preview#22] opened 2015-04-02 07:01 UTC
[Enter steps to reproduce below:]

1. Load Atom

**Atom Version**: 0.189.0
**System**: Mac OS X 10.10.2
**Thrown From**: [api-blueprint-preview](https://github.com/danielgtaylor/atom-api-blueprint-preview) package, v0.3.0

### Stack Trace

Failed to load the api-blueprint-preview package

```
At Module version mismatch. Expected 43, got 41.

Error: Module version mismatch. Expected 43, got 41.
    at Error (native)
    at Object.module.(anonymous function) (ATOM_SHELL_ASAR.js:118:20)
    at Object.module.(anonymous function) (ATOM_SHELL_ASAR.js:118:20)
    at Object.module.(anonymous function) [as .node] (ATOM_SHELL_ASAR.js:118:20)
    at Module.load (module.js:347:32)
    at Function.Module._load (module.js:302:12)
    at Module.require (module.js:357:17)
    at require (module.js:376:17)
    at Object.<anonymous> (/Users/neofreko/.atom/packages/api-blueprint-preview/node_modules/pathwatcher/lib/main.js:6:13)
    at Object.<anonymous> (/Users/neofreko/.atom/packages/api-blueprint-preview/node_modules/pathwatcher/lib/main.js:207:4)
```

### Commands

```
```

### Config

```json
{
  "core": {
    "themes": [
      "atom-dark-ui",
      "atom-dark-syntax"
    ]
  }
}
```

### Installed Packages

```coffee
# User
api-blueprint-preview, v0.3.0
language-docker, v1.1.3

# Dev
No dev packages
```

**Comment by bensleveritt** [comment] 2015-04-02 09:00
Duplicate of https://github.com/danielgtaylor/atom-api-blueprint-preview/issues/21

**Closed** 2015-05-22 04:00 UTC
